#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
SAVE_ROOT="${SAVE_ROOT:-/mnt/data/saves}"
PLANNER_WARMSTART_CKPT="$SAVE_ROOT/improve_multi_agent/improve_babyai_planner_warmstart_v1/global_step_200"
BASE_MODEL_DEFAULT="/home/mavinomichael/AgentGym-RL/models/Qwen2.5-7B-Instruct"

export EXP_NAME="${EXP_NAME:-improve_babyai_planner_frozen_rl_v1}"
export ROLE_LOCAL_OPTIMIZATION=true
export ROLE_LOCAL_ADVANTAGE=true
export ROLE_AUX_REWARDS=true
export MILESTONE_REWARDS=false
export EXECUTOR_PPO_WEIGHT=0.0
export EXECUTOR_KL_WEIGHT=0.0
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
export ROLLOUT_N="${ROLLOUT_N:-1}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-8}"
export ROLLOUT_MAX_TOKENS="${ROLLOUT_MAX_TOKENS:-128}"
export PLANNER_MAX_TOKENS="${PLANNER_MAX_TOKENS:-64}"
export EXECUTOR_MAX_TOKENS="${EXECUTOR_MAX_TOKENS:-64}"
export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.40}"
export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-2048}"
export MAX_NUM_SEQS="${MAX_NUM_SEQS:-32}"
export ACTOR_MAX_TOKEN_LEN_PER_GPU="${ACTOR_MAX_TOKEN_LEN_PER_GPU:-4096}"
export CRITIC_MAX_TOKEN_LEN_PER_GPU="${CRITIC_MAX_TOKEN_LEN_PER_GPU:-4096}"
export USE_REMOVE_PADDING="${USE_REMOVE_PADDING:-true}"
export ACTOR_PARAM_OFFLOAD="${ACTOR_PARAM_OFFLOAD:-true}"
export ACTOR_GRAD_OFFLOAD="${ACTOR_GRAD_OFFLOAD:-true}"
export ACTOR_OPTIMIZER_OFFLOAD="${ACTOR_OPTIMIZER_OFFLOAD:-true}"
export REF_PARAM_OFFLOAD="${REF_PARAM_OFFLOAD:-true}"
export CRITIC_PARAM_OFFLOAD="${CRITIC_PARAM_OFFLOAD:-true}"
export CRITIC_GRAD_OFFLOAD="${CRITIC_GRAD_OFFLOAD:-true}"
export CRITIC_OPTIMIZER_OFFLOAD="${CRITIC_OPTIMIZER_OFFLOAD:-true}"
if [[ ( -z "${MODEL_PATH:-}" || "${MODEL_PATH:-}" == "$BASE_MODEL_DEFAULT" ) && -d "$PLANNER_WARMSTART_CKPT" ]]; then
  export MODEL_PATH="$PLANNER_WARMSTART_CKPT"
fi

bash "$SCRIPT_DIR/run_babyai_joint_rl.sh"
