# Multi-agent extension.
# Derived from: /Users/mavinomichael/PycharmProjects/AgentGym-RL/AgentGym-RL/verl/multi_agent
# Original files left untouched for comparison.

from .prompt_policy import (
    CONTROL_SPEAKER_ID,
    EXECUTOR_SPEAKER_ID,
    PLANNER_SPEAKER_ID,
    ExecutorPayloadValidation,
    PlannerPayloadValidation,
    build_executor_retry_prompt,
    build_executor_turn_prompt,
    build_multi_agent_bootstrap,
    build_multi_agent_instruction,
    build_planner_retry_prompt,
    build_planner_turn_prompt,
    compute_reward_delta,
    detect_invalid_action,
    extract_available_actions_from_observation,
    extract_executor_action,
    is_executor_payload_valid,
    normalize_planner_payload,
    normalize_executor_payload,
    planner_fallback_message,
    validate_planner_payload,
    validate_executor_payload,
)
from .task_registry import TaskProfile, get_task_profile, list_task_profiles

__all__ = [
    "CONTROL_SPEAKER_ID",
    "EXECUTOR_SPEAKER_ID",
    "ExecutorPayloadValidation",
    "PlannerPayloadValidation",
    "PLANNER_SPEAKER_ID",
    "TaskProfile",
    "build_executor_retry_prompt",
    "build_executor_turn_prompt",
    "build_multi_agent_bootstrap",
    "build_multi_agent_instruction",
    "build_planner_retry_prompt",
    "build_planner_turn_prompt",
    "compute_reward_delta",
    "detect_invalid_action",
    "extract_available_actions_from_observation",
    "extract_executor_action",
    "get_task_profile",
    "is_executor_payload_valid",
    "list_task_profiles",
    "normalize_planner_payload",
    "normalize_executor_payload",
    "planner_fallback_message",
    "validate_planner_payload",
    "validate_executor_payload",
]
