# Multi-agent extension.
# Derived from: /Users/mavinomichael/PycharmProjects/AgentGym-RL/AgentGym-RL/verl/workers/rollout/agent_vllm_rollout/vllm_rollout.py
# Original file left untouched for comparison.

from verl.multi_agent.envs.prompt_policy import (
    CONTROL_SPEAKER_ID,
    EXECUTOR_SPEAKER_ID,
    EXECUTOR_REVIEWER_SPEAKER_ID,
    PLANNER_SPEAKER_ID,
    PLANNER_REVIEWER_SPEAKER_ID,
    ROLE_TO_SPEAKER_ID,
    SPEAKER_ID_TO_ROLE,
    ExecutorReviewerDecision,
    ExecutorPayloadValidation,
    PlannerReviewerDecision,
    PlannerPayloadValidation,
    build_executor_reviewer_prompt,
    build_executor_retry_prompt,
    build_executor_turn_prompt,
    build_long_planner_retry_prompt,
    build_long_planner_turn_prompt,
    build_multi_agent_bootstrap,
    build_multi_agent_instruction,
    build_planner_retry_prompt,
    build_planner_reviewer_prompt,
    build_planner_turn_prompt,
    compute_reward_delta,
    detect_invalid_action,
    extract_available_actions_from_observation,
    extract_executor_action,
    is_executor_payload_valid,
    normalize_reviewer_payload,
    parse_executor_reviewer_output,
    parse_planner_reviewer_output,
    normalize_planner_payload,
    normalize_executor_payload,
    planner_fallback_message,
    rewrite_reviewed_planner_plan,
    rewrite_planner_payload,
    validate_reviewed_planner_plan,
    validate_planner_payload,
    validate_executor_payload,
)
from verl.multi_agent.envs.task_registry import get_task_profile

__all__ = [
    "CONTROL_SPEAKER_ID",
    "EXECUTOR_SPEAKER_ID",
    "EXECUTOR_REVIEWER_SPEAKER_ID",
    "ExecutorReviewerDecision",
    "ExecutorPayloadValidation",
    "PlannerPayloadValidation",
    "PLANNER_SPEAKER_ID",
    "PLANNER_REVIEWER_SPEAKER_ID",
    "PlannerReviewerDecision",
    "ROLE_TO_SPEAKER_ID",
    "SPEAKER_ID_TO_ROLE",
    "build_executor_reviewer_prompt",
    "build_executor_retry_prompt",
    "build_executor_turn_prompt",
    "build_long_planner_retry_prompt",
    "build_long_planner_turn_prompt",
    "build_multi_agent_bootstrap",
    "build_multi_agent_instruction",
    "build_planner_retry_prompt",
    "build_planner_reviewer_prompt",
    "build_planner_turn_prompt",
    "compute_reward_delta",
    "detect_invalid_action",
    "extract_available_actions_from_observation",
    "extract_executor_action",
    "get_task_profile",
    "is_executor_payload_valid",
    "normalize_reviewer_payload",
    "parse_executor_reviewer_output",
    "parse_planner_reviewer_output",
    "normalize_planner_payload",
    "normalize_executor_payload",
    "planner_fallback_message",
    "rewrite_reviewed_planner_plan",
    "rewrite_planner_payload",
    "validate_reviewed_planner_plan",
    "validate_planner_payload",
    "validate_executor_payload",
]
