nnodes: 1
n_gpus_per_node: 8
tensor_model_parallel_size: 1
temperature: 0.2
gpu_memory_utilization: 0.45
actor_ppo_max_token_len_per_gpu: 8192
critic_ppo_max_token_len_per_gpu: 8192
max_num_batched_tokens: 4096
max_num_seqs: 64
max_model_len: 8192
model_path: ${oc.env:MODEL_PATH}
env_server_url: ${oc.env:ENV_SERVER_URL}
save_freq: 50
loggers: ['console']
